# Generated by Django 2.0.2 on 2018-11-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeder',
            name='galileo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='credential',
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
        migrations.DeleteModel(
            name='Feeder',
        ),
        migrations.DeleteModel(
            name='Galileo',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
